### PR TITLE
Vampires

### PR DESCRIPTION
**Pull request by tiffanyannhuey**
@Bontgoy Added vampire questionnaire, loop for multiple employees, and plot twist at end.

### CODE REVIEW

**Comment by Bontgoy** [comment]
@tiffanyannhuey I know we are resolving this issue on slack.  If you want at this time you can just send me a link to your vampires file in your repo and I can review from there.

**Comment by tiffanyannhuey** [comment]
@Bontgoy of course - here is the path to the vampire files for 4.4 https://github.com/tiffanyannhuey/phase-0-tracks/blob/master/ruby/vampires.rb

Thanks for helping troubleshoot my git issues

**Comment by Bontgoy** [comment]
Thanks.  I can't do inline since it is not a PR but below are some notes and line suggestions.

**Comment by Bontgoy** [comment]
Line 32:

Consider checking the birth year agains the Ruby time class `Time.now.year` this makes the code more dynamic and allows you the freedom of not having to rewrite the file with hardcoded values as years change.

**Comment by Bontgoy** [comment]
case statement lines 115...:

Consider using nested `if/else` instead to solve these problems.  The conditions should be explicit and while case does solve the problem it can get long and cumbersome and run some unnecessary lines.

Lets consider order of operations here. I understand that the instructions may be guiding you to just put in conditions as they are mentioned. However, we could clean this up and make the file much more efficient by analyzing our conditions for optimal calls and runtime.

If the employee is named "Drake Cula" or "Tu Fang" then we know that they are definitely a vampire. If that's the case, is there any need to even run the rest of the code?

Consider nesting your conditions and creating a strong order of operations for optimized logic and runtime.

```
if name == "Drake Cula" || name == "Tu Fang"
   "definitely a vampire"
else
  if age_check
    do something
  elsif garlic_and_insurance_check
    do something
  else
    do something
  end
end
```

**Pull request merged**
